// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg7Al81nOLzi0UOFL6O1SrseS31UCjut8',
    appId: '1:129427406469:web:d07ed64047da4995c873ec',
    messagingSenderId: '129427406469',
    projectId: 'artvibes-app-fa095',
    authDomain: 'artvibes-app-fa095.firebaseapp.com',
    storageBucket: 'artvibes-app-fa095.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1pqM49q214mrFpmL_KHth-mh3Ai-zE5A',
    appId: '1:129427406469:android:e45c1cf35981f1bfc873ec',
    messagingSenderId: '129427406469',
    projectId: 'artvibes-app-fa095',
    storageBucket: 'artvibes-app-fa095.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaGnssPBsbzjo-OaxHhKuBJn6G-lEVkNY',
    appId: '1:129427406469:ios:0666cf879417a487c873ec',
    messagingSenderId: '129427406469',
    projectId: 'artvibes-app-fa095',
    storageBucket: 'artvibes-app-fa095.firebasestorage.app',
    iosBundleId: 'com.example.artvibesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaGnssPBsbzjo-OaxHhKuBJn6G-lEVkNY',
    appId: '1:129427406469:ios:0666cf879417a487c873ec',
    messagingSenderId: '129427406469',
    projectId: 'artvibes-app-fa095',
    storageBucket: 'artvibes-app-fa095.firebasestorage.app',
    iosBundleId: 'com.example.artvibesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg7Al81nOLzi0UOFL6O1SrseS31UCjut8',
    appId: '1:129427406469:web:fd563acc51773ccdc873ec',
    messagingSenderId: '129427406469',
    projectId: 'artvibes-app-fa095',
    authDomain: 'artvibes-app-fa095.firebaseapp.com',
    storageBucket: 'artvibes-app-fa095.firebasestorage.app',
  );
}